const SUITS=['♠','♥','♣','♦'];
const RANKS=['','A','2','3','4','5','6','7','8','9','10','J','Q','K'];
const THEMES=[{name:'Noite Estrelada',back:'assets/theme-celestial-animal-back.png',colors:['#155a58','#103d46']}];
const $=id=>document.getElementById(id);
let drawCount=1, game, history=[], selected=null, themeIndex=0, moves=0;
const clone=value=>JSON.parse(JSON.stringify(value));
function shuffledDeck(){const deck=[];SUITS.forEach((suit,si)=>{for(let rank=1;rank<=13;rank++)deck.push({suit,rank,red:si===1||si===3,up:false,id:`${suit}${rank}`})});for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}return deck}
function newGame(){const deck=shuffledDeck(),columns=Array.from({length:7},(_,i)=>deck.splice(0,i+1));columns.forEach(col=>col[col.length-1].up=true);game={stock:deck,waste:[],foundations:[[],[],[],[]],columns};history=[];moves=0;selected=null;render();setStatus('Partida nova. Boa sorte!')}
function save(){history.push({game:clone(game),moves});if(history.length>100)history.shift()}
function undo(){if(!history.length){setStatus('Ainda não há jogadas para desfazer.');return}const previous=history.pop();game=previous.game;moves=previous.moves;selected=null;render();setStatus('Jogada desfeita.')}
function setStatus(text){$('status').textContent=text}
function topWaste(){return game.waste.at(-1)}
function suitIndex(card){return SUITS.indexOf(card.suit)}
function faceImage(card){const canvas=document.createElement('canvas');canvas.width=240;canvas.height=340;const c=canvas.getContext('2d'),ink=card.red?'#c84954':'#183b3a',cream='#fff9e9',gold='#e9bd57',teal='#17625b';c.fillStyle=cream;c.beginPath();c.roundRect(1,1,238,338,17);c.fill();c.strokeStyle='#ddd4bf';c.lineWidth=3;c.stroke();c.fillStyle=ink;c.font='bold 37px Georgia';c.textAlign='left';c.textBaseline='top';c.fillText(RANKS[card.rank],14,12);c.font='30px Georgia';c.fillText(card.suit,15,49);c.save();c.translate(240,340);c.rotate(Math.PI);c.textAlign='left';c.font='bold 37px Georgia';c.fillText(RANKS[card.rank],14,12);c.font='30px Georgia';c.fillText(card.suit,15,49);c.restore();if(card.rank>10){c.save();c.translate(120,176);c.fillStyle='#f1e3bc';c.strokeStyle=ink;c.lineWidth=5;c.beginPath();c.roundRect(-73,-109,146,218,26);c.fill();c.stroke();c.fillStyle=teal;c.beginPath();c.ellipse(0,-32,51,54,0,0,Math.PI*2);c.fill();c.fillStyle=gold;c.beginPath();c.arc(0,-30,32,0,Math.PI*2);c.fill();c.fillStyle=ink;c.beginPath();c.moveTo(-25,-52);c.lineTo(-18,-96);c.lineTo(1,-64);c.lineTo(20,-96);c.lineTo(28,-52);c.closePath();c.fill();c.fillStyle='#fff5dc';c.beginPath();c.arc(-11,-31,4,0,Math.PI*2);c.arc(11,-31,4,0,Math.PI*2);c.fill();c.fillStyle=ink;c.fillRect(-8,2,16,5);c.font='bold 19px Georgia';c.textAlign='center';c.fillText({11:'VALETE',12:'DAMA',13:'REI'}[card.rank],0,76);c.restore()}else{const positions={1:[[0,0]],2:[[-.0,-.55],[0,.55]],3:[[0,-.58],[0,0],[0,.58]],4:[[-.42,-.5],[.42,-.5],[-.42,.5],[.42,.5]],5:[[-.42,-.5],[.42,-.5],[0,0],[-.42,.5],[.42,.5]],6:[[-.42,-.55],[.42,-.55],[-.42,0],[.42,0],[-.42,.55],[.42,.55]],7:[[-.42,-.6],[.42,-.6],[-.42,-.2],[.42,-.2],[0,0],[-.42,.45],[.42,.45]],8:[[-.42,-.6],[.42,-.6],[-.42,-.2],[.42,-.2],[-.42,.2],[.42,.2],[-.42,.6],[.42,.6]],9:[[-.4,-.62],[.4,-.62],[-.4,-.31],[.4,-.31],[0,0],[-.4,.31],[.4,.31],[-.4,.62],[.4,.62]],10:[[-.4,-.65],[.4,-.65],[-.4,-.4],[.4,-.4],[-.4,-.13],[.4,-.13],[-.4,.13],[.4,.13],[-.4,.4],[.4,.4]]}[card.rank];c.fillStyle=ink;c.textAlign='center';c.textBaseline='middle';c.font=card.rank===1?'86px Georgia':'37px Georgia';positions.forEach(([x,y])=>{c.save();c.translate(120+x*65,176+y*105);if(y>0)c.rotate(Math.PI);c.fillText(card.suit,0,0);c.restore()})}return canvas.toDataURL('image/png')}
function cardMarkup(card,origin,index,offset){if(!card.up)return `<div class="card back" role="img" aria-label="Carta virada para baixo" style="top:${offset}px" data-origin="${origin}" data-index="${index}"></div>`;const chosen=selected?.origin===origin&&selected?.index===index?' selected':'';return `<img class="card face${card.red?' red':' black'}${chosen}" src="${faceImage(card)}" role="button" tabindex="0" alt="${RANKS[card.rank]} de ${card.suit}" style="top:${offset}px" data-origin="${origin}" data-index="${index}">`}
function render(){const stock=$('stock');stock.classList.toggle('empty',!game.stock.length);stock.innerHTML=game.stock.length?'':`<span aria-hidden="true">↻</span>`;const waste=$('waste');waste.innerHTML=topWaste()?cardMarkup(topWaste(),'waste',game.waste.length-1,0):'';const foundations=$('foundations');foundations.innerHTML=SUITS.map((suit,i)=>`<button class="foundation" data-foundation="${i}" aria-label="Fundação ${suit}">${game.foundations[i].length?cardMarkup(game.foundations[i].at(-1),'foundation',i,0):suit}</button>`).join('');const columns=$('columns');columns.innerHTML=game.columns.map((col,c)=>`<div class="column" data-column="${c}" style="min-height:calc(var(--card-h) + ${Math.max(0,col.length-1)*22}px)">${col.map((card,i)=>cardMarkup(card,`column-${c}`,i,i*22)).join('')}</div>`).join('');$('moves').textContent=`${moves} ${moves===1?'jogada':'jogadas'}`;document.querySelectorAll('[data-draw]').forEach(btn=>btn.classList.toggle('selected',Number(btn.dataset.draw)===drawCount));document.querySelectorAll('.card.face').forEach(card=>card.addEventListener('click',onCard));document.querySelectorAll('.card.face').forEach(card=>card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onCard(e)}}));document.querySelectorAll('.column').forEach(col=>col.addEventListener('click',onColumn));document.querySelectorAll('.foundation').forEach(el=>el.addEventListener('click',onFoundation))}
function sourceCard(origin,index){if(origin==='waste')return game.waste.at(-1);if(origin?.startsWith('column-'))return game.columns[Number(origin.split('-')[1])][index];return null}
function extract(origin,index){if(origin==='waste')return [game.waste.pop()];const c=Number(origin.split('-')[1]),pile=game.columns[c],moving=pile.splice(index);if(pile.length)pile.at(-1).up=true;return moving}
function select(origin,index){const card=sourceCard(origin,index);if(!card?.up)return;selected={origin,index};render()}
function onCard(event){event.stopPropagation();const el=event.currentTarget,origin=el.dataset.origin,index=Number(el.dataset.index);if(selected){if(selected.origin===origin&&selected.index===index){selected=null;render();return}if(origin.startsWith('column-')&&moveToColumn(Number(origin.split('-')[1])) )return;if(origin==='foundation'&&moveToFoundation(Number(index)))return}select(origin,index)}
function moveToColumn(target){if(!selected)return false;const moving=sourceCard(selected.origin,selected.index);if(!moving)return false;const dest=game.columns[target],top=dest.at(-1);if((!top&&moving.rank===13)||(top&&top.up&&top.red!==moving.red&&top.rank===moving.rank+1)){save();const cards=extract(selected.origin,selected.index);dest.push(...cards);moves++;selected=null;render();checkWin();return true}return false}
function moveToFoundation(foundationIndex){if(!selected)return false;const moving=sourceCard(selected.origin,selected.index);if(!moving)return false;if(selected.origin.startsWith('column-')&&selected.index!==game.columns[Number(selected.origin.split('-')[1])].length-1)return false;const pile=game.foundations[foundationIndex],top=pile.at(-1);if((!top&&moving.rank===1)||(top&&top.suit===moving.suit&&moving.rank===top.rank+1)){save();pile.push(...extract(selected.origin,selected.index));moves++;selected=null;render();checkWin();return true}return false}
function onColumn(event){if(event.target.closest('.card'))return;const index=Number(event.currentTarget.dataset.column);if(!selected){const pile=game.columns[index];if(pile.length&&!pile.at(-1).up){save();pile.at(-1).up=true;moves++;render()}return}if(moveToColumn(index))return;const pile=game.columns[index];if(pile.length&&!pile.at(-1).up){save();pile.at(-1).up=true;moves++;selected=null;render()}}
function onFoundation(event){const slot=Number(event.currentTarget.dataset.foundation);if(selected&&moveToFoundation(slot))return;if(!selected&&game.waste.length){selected={origin:'waste',index:game.waste.length-1};if(moveToFoundation(slot))return;selected=null;render()}}
function draw(){selected=null;if(game.stock.length){save();for(let i=0;i<drawCount&&game.stock.length;i++){const card=game.stock.pop();card.up=true;game.waste.push(card)}moves++;render();return}if(game.waste.length){save();game.stock=game.waste.reverse().map(card=>({...card,up:false}));game.waste=[];moves++;render()}}
function checkWin(){if(game.foundations.every(pile=>pile.length===13))setStatus(`Vitória! Você terminou em ${moves} jogadas.`)}
$('stock').addEventListener('click',draw);$('newGame').addEventListener('click',newGame);$('undo').addEventListener('click',undo);
document.querySelectorAll('[data-draw]').forEach(btn=>btn.addEventListener('click',()=>{drawCount=Number(btn.dataset.draw);render()}));
$('themeButton').addEventListener('click',()=>setStatus('Este é o primeiro tema. Os outros estilos que você enviou entram como temas separados.'));
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
newGame();

